In [1]:
import numpy as np
import matplotlib.pylab as plt
import pandas as pd
import matplotlib.pylab as plt
import sklearn.preprocessing as sk 
import tensorflow as tf

2023-02-06 00:24:51.546958: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
#original emg data
df0_emg = pd.read_csv("0.csv", header=None )
df1_emg = pd.read_csv("1.csv", header=None )
df2_emg = pd.read_csv("2.csv", header=None )
df3_emg = pd.read_csv("3.csv", header=None )

In [3]:
df0_emg.head()

0    1    2    3     4     5      6     7     8    9   ...    55    56  \
0  26.0  4.0  5.0  8.0  -1.0 -13.0 -109.0 -66.0  -9.0  2.0  ... -28.0  61.0   
1 -47.0 -6.0 -5.0 -7.0  13.0  -1.0   35.0 -10.0  10.0 -4.0  ... -25.0  47.0   
2 -19.0 -8.0 -8.0 -8.0 -21.0  -6.0  -79.0  12.0   0.0  5.0  ... -83.0   7.0   
3   2.0  3.0  0.0  2.0   0.0  22.0  106.0 -14.0 -16.0 -2.0  ... -38.0 -11.0   
4   6.0  0.0  0.0 -2.0 -14.0  10.0  -51.0   5.0   7.0  0.0  ...  38.0 -35.0   

    57   58    59    60    61     62    63  64  
0  4.0  8.0   5.0   4.0  -7.0  -59.0  16.0   0  
1  6.0  6.0   5.0  13.0  21.0  111.0  15.0   0  
2  7.0  1.0  -8.0   7.0  21.0  114.0  48.0   0  
3  4.0  7.0  11.0  33.0  39.0  119.0  43.0   0  
4 -8.0  2.0   6.0 -13.0 -24.0 -112.0 -69.0   0  

[5 rows x 65 columns]

In [4]:
allFiles=['0.csv','1.csv','2.csv','3.csv']

list = []
for file in allFiles:
    read = pd.read_csv(file, header = None)
    list.append(read)
df = pd.concat(list)

In [5]:
df0_emg.shape

(2910, 65)

In [6]:
x = df.loc[:,0:63]
y = df[64]

In [21]:
x.shape

(11678, 64)

In [23]:
arr=np.array(x)

In [38]:
x = np.reshape(arr,(11678,8,8))

In [39]:
print(x)

[[[  26.    4.    5. ...  -13. -109.  -66.]
  [  -9.    2.    4. ...  -30. -119.  -45.]
  [  17.    6.   -1. ...   20.   91.   71.]
  ...
  [  -7.   -6.  -12. ...  -16.  -67.   -8.]
  [ -27.    1.    1. ...  -11.   21.  -28.]
  [  61.    4.    8. ...   -7.  -59.   16.]]

 [[ -47.   -6.   -5. ...   -1.   35.  -10.]
  [  10.   -4.    0. ...  -33.  -48.  -52.]
  [  34.   10.    5. ...   63.   76.   49.]
  ...
  [   7.   -2.    0. ...   -3.    0.   -8.]
  [ -40.   -4.   -1. ...   -2. -105.  -25.]
  [  47.    6.    6. ...   21.  111.   15.]]

 [[ -19.   -8.   -8. ...   -6.  -79.   12.]
  [   0.    5.    4. ...    9.   33.   34.]
  [  -1.   -4.   -3. ...  -11.  -85.  -12.]
  ...
  [  27.    7.    4. ...   23.  127.   69.]
  [ -25.  -12.   -9. ...  -33. -128.  -83.]
  [   7.    7.    1. ...   21.  114.   48.]]

 ...

 [[  -1.   -3.   -1. ...   38.   -1.   36.]
  [ -10.    1.    4. ...   33.   -2.   -1.]
  [  -1.    2.   -3. ...  -25.    0.    3.]
  ...
  [  -6.   -5.   -4. ...  -10.   -4.   -

In [45]:
x.shape

(11678, 8, 8)

In [9]:
y.unique()

array([0, 1, 2, 3])

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42,stratify=y)

In [52]:
# Define the model
model = tf.keras.models.Sequential([
                                                         
  # Add convolutions and max pooling
  tf.keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(8, 8, 1)),
  tf.keras.layers.MaxPooling2D(2, 2),
  tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
 # tf.keras.layers.MaxPooling2D(2,2),

  # Add the same layers as before
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(36, activation='relu'),
  tf.keras.layers.Dense(4, activation='softmax')
])

In [53]:
model.compile(optimizer = tf.optimizers.Adam(),
              loss = 'sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

Epoch 1/5
274/274 [==============================] - 1s 1ms/step - loss: 0.5570 - accuracy: 0.7845
Epoch 2/5
274/274 [==============================] - 0s 1ms/step - loss: 0.2620 - accuracy: 0.9108
Epoch 3/5
274/274 [==============================] - 0s 1ms/step - loss: 0.1950 - accuracy: 0.9299
Epoch 4/5
274/274 [==============================] - 0s 1ms/step - loss: 0.1718 - accuracy: 0.9412
Epoch 5/5
274/274 [==============================] - 0s 1ms/step - loss: 0.1467 - accuracy: 0.9467


In [54]:
est_loss = model.evaluate(x_test, y_test)

92/92 [==============================] - 0s 668us/step - loss: 0.1861 - accuracy: 0.9397
